targets:
  $default:
    sources:
      - lib/**
      - test/**
    builders:
      use_entity_sync_builder:
        generate_for:
          - lib/core/services/entity_sync.dart
        options:
          apply_builders_to_root: false

builders:
  use_entity_sync_builder:
    import: "package:entity_sync_generator/entity_sync_generator.dart"
    builder_factories: ["useEntitySyncBuilder"]
    build_extensions: { ".dart": [".use_entity_sync_builder.g.part"] }
    auto_apply: none 
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

