name: entity_sync_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  entity_sync:
    git:
      url: https://github.com/qBozo/entity_sync
      ref: dart3-fixes
  analyzer: ">=0.40.0 <=2.1.0"

  source_gen: ^0.9.4
  build: ^1.6.0
#
#dev_dependencies:
#  test: ^1.16.5
