name: entity_sync_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  entity_sync:
    git:
      url: https://github.com/qBozo/entity_sync
      ref: dart3-fixes
  analyzer: ">=4.0.0 <7.0.0"

  source_gen: ^1.2.2
  build: ^2.4.1
#
dev_dependencies:
#  test: ^1.16.5
  build_runner: ^2.4.8
  source_gen: ^1.2.2

dependency_overrides:
  file: ^7.0.1
